### PR TITLE
0.5.5 hf99513

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/emd-feedstock/pull/6

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Review by larsoner — COMMENTED** [review]
Reqs updated to hopefully properly reflect https://gitlab.com/emd-dev/emd/-/blob/v0.5.5/setup.py, ready for review/merge from my end!

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Looks good to me! @ajquinn can you merge please if you have a minute?

**Comment by AJQuinn** [comment]
Amazing - thank you @larsoner & @hoechenberger. I'd spotted some deps were a bit out after my last minor release but hadn't got around to sorting it. Happy to merge this now.

I'm planning to improve how dependencies are handled and checked in emd in the next release, likely coming this week. Hopefully if the version changes here are maintained this wouldn't affect things on your side?

**Comment by AJQuinn** [comment]
PS - I didn't realise EMD was distributed in the MNE installer... very cool! 

Please let me know if any other tweaks or changes come up.

**Comment by larsoner** [comment]
> Hopefully if the version changes here are maintained this wouldn't affect things on your side?

Indeed things should be fine as long as no crazy pinning happens in the process -- then conflicts can occur with other packages we want that have pins of their own.

**Pull request merged**
