### PR TITLE
MAINT: Release upper bound on NumPy

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

A year ago I relaxed the upper bound on the NumPy version in https://github.com/conda-forge/emd-feedstock/pull/7 . This PR removes it completely as 1) it's going to keep causing problems and 2) it doesn't appear in upstream setup.py or requirements.txt, e.g.:

https://gitlab.com/emd-dev/emd/-/blob/master/requirements.txt#L2

Should fix this issue:

<details>
<summary>EMD not 3.11 compatible because of NumPy pin</summary>

```
Could not solve for environment specs
The following packages are incompatible
├─ emd 0.5.5**  is installable and it requires
│  └─ numpy <1.22,>=1.17  with the potential options
│     ├─ numpy [1.17.0|1.17.1|...|1.19.2] would require
│     │  └─ python >=3.6,<3.7.0a0  with the potential options
│     │     ├─ python [3.6.0|3.6.1|...|3.6.9], which can be installed;
│     │     ├─ python 3.6.3 would require
│     │     │  └─ zlib 1.2.8 , which can be installed;
│     │     └─ python [3.6.3|3.6.4|3.6.5] would require
│     │        └─ zlib 1.2.11 , which can be installed;
│     ├─ numpy [1.17.0|1.17.1|...|1.21.5] would require
│     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│     ├─ numpy [1.17.3|1.17.4|...|1.21.5] would require
│     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│     ├─ numpy [1.17.5|1.18.1|...|1.19.5] would require
│     │  ├─ python >=3.6,<3.7.0a0  with the potential options
│     │  │  ├─ python [3.6.0|3.6.1|...|3.6.9], which can be installed;
│     │  │  ├─ python 3.6.3, which can be installed (as previously explained);
│     │  │  └─ python [3.6.3|3.6.4|3.6.5], which can be installed (as previously explained);
│     │  └─ python_abi 3.6.* *_cp36m, which can be installed;
│     ├─ numpy [1.17.5|1.18.1|...|1.21.6] would require
│     │  ├─ python >=3.7,<3.8.0a0 , which can be installed;
│     │  └─ python_abi 3.7.* *_cp37m, which can be installed;
│     ├─ numpy [1.17.5|1.18.1|...|1.21.6] would require
│     │  ├─ python >=3.8,<3.9.0a0 , which can be installed;
│     │  └─ python_abi 3.8.* *_cp38, which can be installed;
│     ├─ numpy [1.18.1|1.18.4|...|1.19.5] would require
│     │  └─ python_abi 3.6 *_pypy36_pp73, which requires
│     │     └─ python 3.6.* *_73_pypy, which can be installed;
│     ├─ numpy [1.19.2|1.19.4|...|1.21.6] would require
│     │  ├─ python >=3.9,<3.10.0a0 , which can be installed;
│     │  └─ python_abi 3.9.* *_cp39, which can be installed;
│     ├─ numpy [1.19.5|1.20.0|...|1.21.5] would require
│     │  └─ python_abi 3.7 *_pypy37_pp73, which requires
│     │     └─ python 3.7.* *_73_pypy, which can be installed;
│     ├─ numpy [1.19.5|1.20.3|1.21.5|1.21.6] would require
│     │  └─ python_abi 3.8 *_pypy38_pp73, which can be installed;
│     ├─ numpy [1.19.5|1.20.3|1.21.5|1.21.6] would require
│     │  └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
│     ├─ numpy [1.21.3|1.21.4|1.21.5|1.21.6] would require
│     │  ├─ python >=3.10,<3.11.0a0 , which can be installed;
│     │  └─ python_abi 3.10.* *_cp310, which can be installed;
│     ├─ numpy [1.19.2|1.19.5|...|1.21.5] would require
│     │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│     └─ numpy [1.21.2|1.21.5] would require
│        └─ python >=3.10,<3.11.0a0 , which can be installed;
├─ mne 1.4dev0 *_20230503 is uninstallable because it requires
│  └─ openmeeg >=2.5.6 , which requires
│     └─ libzlib >=1.2.13,<1.3.0a0 , which requires
│        └─ zlib 1.2.13 *_4, which conflicts with any installable versions previously reported;
└─ python 3.11.3**  is uninstallable because it conflicts with any installable versions previously reported.
```

</details>

@AJQuinn I added myself as a maintainer since I do this sort of stuff for a lot of packages (mne-*, mayavi, etc.) but I can remove myself if you want.

Closes #9
Closes #10
Closes #11

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Oh no, this actually needs a new EMD release as the pin was released in https://gitlab.com/emd-dev/emd/-/commit/97fedf794e0fb51d18ca92262d302b9ca0f31d4e :(

@ajquinn any chance for a new release? If not I could patch out the requirement in the `setup.py` that's in the source tarball but that's a bit ugly

**Comment by larsoner** [comment]
... in other words, your current PyPI release (and this on conda-forge) are both Python 3.11-incompatible because they pin to a numpy version too old to support Python 3.11.

**Comment by AJQuinn** [comment]
Hi @larsoner -  thanks for looking into this. 

I haven't been able to get a new release out for a while. Didn't realise that these incompatibilities had crept up.. I'll sort it on PyPI in the next few days. Is this blocking something in the meantime? I'll prioritise if so.

**Comment by larsoner** [comment]
Can't release the MNE-Python installers using Python 3.11 and include EMD. But also the 3.11-compatible Numba release feedstock has also stalled (probably for another week or two?) so EMD isn't the only limiting factor at the moment :)

**Comment by AJQuinn** [comment]
Ok, good to know. I'll take a look ASAP!

**Comment by AJQuinn** [comment]
Hey @larsoner - apologies for the delay on this. I've got a version release ready to go, just wanted to double check its going to do what you need...

short story: I'm now explicitly testing against python 3.11 and it's passing without requiring any suspicious pins. I'll release this on PyPI.org and that should trigger a new PR for that version here (I think..). 

Are you happy to go ahead with that new PR? or are there changes here that I could incorporate in the release?

**Comment by larsoner** [comment]
Go for it! I might adapt this PR to be a version update if I can go faster than the auto update bot :)

**Comment by AJQuinn** [comment]
Ok, I've done a (couple of) release(s)...

Up to v0.6.1 now due to a website issue in 0.6.0. There is an auto PR for 0.6.0 but perhaps better to go ahead with 0.6.1 for consistency with PyPI unless its straightforward to run through both. Let me know if there is anything I can do.

Thanks for taking a look at this.

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
>  There is an auto PR for 0.6.0 but perhaps better to go ahead with 0.6.1 for consistency with PyPI unless its straightforward to run through both. Let me know if there is anything I can do.

Yeah feel free to close the 0.6.0 and 0.6.1 PRs and merge this if you're happy. Should come back green any minute :crossed_fingers:

**Comment by larsoner** [comment]
@AJQuinn looks like there is a problem with your `sdist`:
```
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/emd_1684853365444/work/setup.py", line 27, in <module>
      reqs = (HERE / "requirements.txt").read_text()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/conda/feedstock_root/build_artifacts/emd_1684853365444/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/pathlib.py", line 1058, in read_text
      with self.open(mode='r', encoding=encoding, errors=errors) as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/conda/feedstock_root/build_artifacts/emd_1684853365444/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/pathlib.py", line 1044, in open
      return io.open(self, mode, buffering, encoding, errors, newline)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/emd_1684853365444/work/requirements.txt'
```
I can confirm locally that `requirements.txt` is not in it:
```
emd-0.6.1$ ls -alt
total 76
drwxr-xr-x 12 larsoner larsoner 12288 May 23 13:51 ..
drwxr-xr-x  4 larsoner larsoner  4096 May 22 17:26 .
drwxr-xr-x  2 larsoner larsoner  4096 May 22 17:26 emd
drwxr-xr-x  2 larsoner larsoner  4096 May 22 17:26 emd.egg-info
-rw-r--r--  1 larsoner larsoner  3290 May 22 17:26 PKG-INFO
-rw-r--r--  1 larsoner larsoner   538 May 22 17:26 setup.cfg
-rw-r--r--  1 larsoner larsoner  2444 May 22 15:12 setup.py
-rw-r--r--  1 larsoner larsoner  2183 Aug 23  2022 README.md
-rw-r--r--  1 larsoner larsoner 35149 Feb  1  2020 LICENSE.txt
```

**Comment by AJQuinn** [comment]
Yes, saw this yesterday. It's down to a change I made to keep readthedocs happy...

Have a fix here by including the reqs in a `MANIFEST.in` https://gitlab.com/emd-dev/emd/-/commit/40750f2002e0e61421255751f5d3daa7ab0ad4ad - The package builds with the reqs locally now. Will get it out this afternoon.

Tricky stuff! apologies for this getting complex...

**Comment by larsoner** [comment]
> Tricky stuff! apologies for this getting complex...

No problem, I'm sure it's (much) quicker for my iterations at this end than at the fix-and-release end :)

**Comment by larsoner** [comment]
Green!

**Pull request merged**
